### ISSUE TITLE
Build scheduling manager steel thread

### ISSUE THREAD

**Issue by wjbuys** [blox/blox#261]
The outcome from #238 was that we'll build the following:

We wire up the two event sources to the scheduling manager function:

![image](https://user-images.githubusercontent.com/31602/31101005-a1d0c746-a780-11e7-8569-6e993c6c23d3.png)

This needs to parallelize over clusters, somehow. We can either do that before the manager (i.e. an additional lambda function consumes only the CWE Cron Event, and then kicks off a manager per cluster), or parallelize inside the manager itself. For now, I'm just going to do this serially in the manager.

Once the manager has a single (cluster, environment) mapping, it invokes the scheduling function for that tuple. Since we don't want to re-query cluster state for every environment, we query it once from the manager, and pass it into the scheduling function along with the environment ID.

![image](https://user-images.githubusercontent.com/31602/31102090-80f91f32-a785-11e7-9483-3e8175251f09.png)

The scheduling function then calls the data service to describe the environment's target by ID. Using this description along with the cluster state, it calculates which tasks to launch/terminate, and calls the ECS control plane.

Finally, we may have to wait for all scheduling functions to complete in the manager function.

This issue is to set up the lambda function definitions and interfaces, with stub implementations.

- [x] set up local test harness
- [x] define lambda structure
- [x] figure out lambda-to-lambda call interface
- [x] configure cloudformation template for lambdas
- [x] SingleTask scheduling implementation
- [x] implement ECSState interface to get cluster state snapshot
- [x] integrate with DataService implementation

#### Followup tasks
These tasks are operational/incremental improvements that we should revisit immediately after this issue, broken out as cards on our planning board:
- [figure out error marshaling between functions](https://github.com/blox/blox/projects/2#card-5333492)
- [migrate from custom `CloudWatchEvent` type to built-in `ScheduledEvent` type](https://github.com/blox/blox/projects/2#card-5333521)
- [add API integration test suite that runs against beta stack (needs a beta stack)](https://github.com/blox/blox/projects/2#card-5333497)
- [add logging/error handling `RequestHandler` wrappers](https://github.com/blox/blox/projects/2#card-5333509)

**Comment by wjbuys** [comment]
We've discussed this, and we probably need to have a separate lambda function for the call from the reconciliation event, so that we can parallelize on all clusters. I'll update the description above.

**Comment by wjbuys** [comment]
Okay, I have this mostly working, but I've taken some shortcuts to get it all working in Lambda. I'll clean it up a bit tomorrow, and then start breaking off pull requests.

**Comment by wjbuys** [comment]
As an aside, I've been trying to use the new AWS SDK v2 for Java, since it adds true non-blocking IO for downstream calls to Lambda using Netty. However, it looks like [the native `epoll` Netty channel doesn't work on Lambda](https://github.com/aws/aws-sdk-java-v2/issues/193). Performance using the `nio` channel as I've got it configured now doesn't quite get to 100s of connections, so I'll have to follow up on this again.

**Comment by wjbuys** [comment]
Here's the rough structure:

- `reconciler(CloudWatchEvent)` function: triggered by CloudWatch event. Calls `DataService.listClusters()` to get all clusters. Then concurrently invokes `state-dispatcher` for every cluster using non-blocking IO, and waits for all invocations to complete.
- `state-dispatcher(List<Cluster>)` function: triggered by `reconciler`. Calls ECS state facade to get full snapshot of cluster state for given cluster ID, and calls `DataService.listEnvironmentsByCluster` to get all environments. Then concurrently invokes `scheduler` for each environment.
- `scheduler(EnvironmentId, ClusterStateSnapshot)` function: triggered by `state-dispatcher`. Calls `DataService.describeEnvironment(environmentId)` to get the target environment version, and loads the appropriate `DeploymentStrategy` for that environment. Then it calculates which tasks to run/stop based on the current state and the target environment version.

For now, I've just put all of these in the `scheduling-manager` project in different Java packages, since there's some common code for invoking Lambda functions in a type-safe way, and some common Spring glue. My next step is to break these into separate projects per lambda function, so that we don't need all the code from every function in every other function.

However, we probably still want to deploy these using a single CloudFormation template, since the function names have to be wired together. I'm thinking of a project structure like:

```
Project lambda-client/
Project scheduling/
  Project reconciler-fn/
  Project state-dispatcher-fn/
  Project scheduler-fn/
  cloudformation/template.yml
```

Right now it uses a stub of DataService which returns an arbitrary list of 100 clusters, each with 10 environments, to get a ballpark idea of performance. Looks like once everything is warm, the top-level reconciler finishes in ~20s, with each `scheduler` function artificially delaying for 2s.

However, when cold, everything times out; we may have to make an explicit pre-warming function that asynchronously warms enough scheduler functions for the total number of environments in the system.

**Comment by wjbuys** [comment]
I'm trying out using `InvocationType.Event` to fire off the state dispatcher function from the reconciler function, since it's taking ~30s to wait for those to complete with `InvocationType.RequestReply`. However, somehow this is not playing nice with Netty's async client:

```
java.util.NoSuchElementException: HttpStreamsClientHandler#0-body-publisher: java.util.concurrent.CompletionException
java.util.concurrent.CompletionException: java.util.NoSuchElementException: HttpStreamsClientHandler#0-body-publisher
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
at software.amazon.awssdk.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.handle(AsyncRetryableStage.java:160)
at software.amazon.awssdk.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.lambda$execute$0(AsyncRetryableStage.java:143)
at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
at software.amazon.awssdk.http.pipeline.stages.MakeAsyncHttpRequestStage$ResponseHandler.exceptionOccurred(MakeAsyncHttpRequestStage.java:185)
at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.lambda$exceptionCaught$1(ResponseHandler.java:120)
at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.runAndLogError(ResponseHandler.java:132)
at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.exceptionCaught(ResponseHandler.java:119)
at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
at com.typesafe.netty.HandlerSubscriber.exceptionCaught(HandlerSubscriber.java:157)
at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
at io.netty.channel.AbstractChannelHandlerContext.notifyHandlerException(AbstractChannelHandlerContext.java:850)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:364)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1273)
at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1084)
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:979)
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:403)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:306)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.NoSuchElementException: HttpStreamsClientHandler#0-body-publisher
at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1080)
at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:434)
at com.typesafe.netty.http.HttpStreamsHandler.removeHandlerIfActive(HttpStreamsHandler.java:328)
at com.typesafe.netty.http.HttpStreamsHandler.handleReadHttpContent(HttpStreamsHandler.java:189)
at com.typesafe.netty.http.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:165)
at com.typesafe.netty.http.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:148)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
... 26 more
```

**Comment by wjbuys** [comment]
I've opened aws/aws-sdk-java-v2#202 for the problem using the Async client for Event invocations.

**Comment by wjbuys** [comment]
I've broken out the follow-up items into cards on our planning board, I'd consider this feature done once https://github.com/blox/blox/pull/275 is merged.
