### ISSUE TITLE
Exception mapping error between JsonRPCServer and client

### ISSUE THREAD

**Issue by narehayrapetyan** [blox/blox#315]
Exception mapping does not work correctly. The return payload on the JsonRPCLambdaServer side returns:
`
{"jsonrpc":"2.0","id":"1380430143","error":{"code":-32001,"message":"environment with id EnvironmentId(environmentName=testfd33348b-b0d2-4c9d-863b-c29792719376, accountId=12345678912, cluster=clustere57c7631-8441-4b27-990a-afd4bfef8b19) already exists","data":{"exceptionTypeName":"com.amazonaws.blox.dataservicemodel.v1.exception.ResourceExistsException","message":"environment with id EnvironmentId(environmentName=testfd33348b-b0d2-4c9d-863b-c29792719376, accountId=12345678912, cluster=clustere57c7631-8441-4b27-990a-afd4bfef8b19) already exists"}}}`

but the client interprets it as:

```
java.lang.NullPointerException
        at com.googlecode.jsonrpc4j.JsonRpcClient.handleErrorResponse(JsonRpcClient.java:270)
        at com.googlecode.jsonrpc4j.JsonRpcClient.readResponse(JsonRpcClient.java:196)
        at com.googlecode.jsonrpc4j.JsonRpcClient.readResponse(JsonRpcClient.java:529)
        at com.amazonaws.blox.jsonrpc.JsonRpcLambdaClient.readResponse(JsonRpcLambdaClient.java:150)
        at com.amazonaws.blox.jsonrpc.JsonRpcLambdaClient.lambda$invokeAsync$2(JsonRpcLambdaClient.java:112)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at software.amazon.awssdk.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.handle(AsyncRetryableStage.java:152)
  
```

**Comment by wjbuys** [comment]
It looks like the default exception mapper in jsonrpc4j only supports exceptions with no-argument or message-argument constructors:

https://github.com/briandilley/jsonrpc4j/blob/d749762c9295b92d893677a8c7be2a14dd43b3bb/src/main/java/com/googlecode/jsonrpc4j/DefaultExceptionResolver.java#L56-L89

Since the `ResourceExistsException` class takes the resourceId and resourceType as string arguments, it hits line 86, resulting in `throw null`.

The fix is to add a custom exception mapper for our rich exception types, or to add a single-argument constructor to our exception types for unmarshalling purposes.

**Comment by wjbuys** [comment]
So, I think it's worth trying to add a simple Jackson-based ErrorResolver (for serialization) and ExceptionMapper (for deserialization) to handle exceptions the same way that requests/responses are handled. But if this turns out to be more complicated than expected, we'll have to think of another way to deal with this.
